### ISSUE TITLE
'com_intel_bluetooth_BluetoothStackOSX.h' file not found 

### ISSUE THREAD

**Issue by imanzano** [hcarver/bluecove#4]
Hi,

When I run mvn package I got 

bluecove/bluecove/src/main/c/intelbth/OSXStack.h:35:10: fatal error: 'com_intel_bluetooth_BluetoothStackOSX.h' file not found

Do you know why ? I read that this files is generted....but It doesn't work in my machine with OSX 10.10
Any idea?

Thanks!

**Comment by hcarver** [comment]
Hi @imanzano, I'd guess it's because Mavericks calls the file by a different name, but I don't know for sure. I haven't touched this repo in a while but if you're able to fix the problem, please do open up a pull request for it!
